# vim: ts=8 sw=8 noexpandtab ft=make

# Automatically generated module dependencies for
# module `tdigest_mut' in source file `tdigest_mut.m'.
# Generated by Mercury compiler version rotd-2024-06-15
# configured for x86_64-pc-linux-gnu.

# RULE date_file_deps
# target group names:
#   dates_and_err
# source group names:
#   source
#   long deps
#   short deps
#   type_repn self dep
tdigest_mut.optdate tdigest_mut.trans_opt_date tdigest_mut.err tdigest_mut.c_date tdigest_mut.java_date : \
		tdigest_mut.m \
	\
		builtin.int \
		float.int \
		int.int \
		private_builtin.int \
		tdigest.int \
	\
		array.int2 \
		assoc_list.int2 \
		enum.int2 \
		list.int2 \
		map.int2 \
		maybe.int2 \
		pair.int2 \
		pretty_printer.int2 \
		term.int2 \
		term_context.int2 \
		tree234.int2 \
		type_desc.int2 \
		univ.int2 \
	\
		tdigest_mut.int

# RULE mh_and_mih_on_c
tdigest_mut.mh tdigest_mut.mih : tdigest_mut.c

ifeq ($(findstring java,$(GRADE)),java)

# RULE module_dep_on_java
tdigest_mut.module_dep : jmercury/tdigest_mut.java

else

# RULE module_dep_on_c
tdigest_mut.module_dep : tdigest_mut.c

endif # conditional fragment

# RULE self_and_parent_date_deps
# target group names:
#   date files
# source group names:
#   source
#   long dep int3s
#   short dep int3s
tdigest_mut.date tdigest_mut.date0 : \
		tdigest_mut.m \
	\
		builtin.int3 \
		float.int3 \
		int.int3 \
		private_builtin.int3 \
		tdigest.int3 \
	\
		array.int3 \
		assoc_list.int3 \
		enum.int3 \
		list.int3 \
		map.int3 \
		maybe.int3 \
		pair.int3 \
		pretty_printer.int3 \
		term.int3 \
		term_context.int3 \
		tree234.int3 \
		type_desc.int3 \
		univ.int3

# RULE self_and_parent_date0_deps
# target group names:
#   date0s
# source group names:
#   source
#   long dep int3s
#   short dep int3s
tdigest_mut.date0 : \
		tdigest_mut.m \
	\
		builtin.int3 \
		float.int3 \
		int.int3 \
		private_builtin.int3 \
		tdigest.int3 \
	\
		array.int3 \
		assoc_list.int3 \
		enum.int3 \
		list.int3 \
		map.int3 \
		maybe.int3 \
		pair.int3 \
		pretty_printer.int3 \
		term.int3 \
		term_context.int3 \
		tree234.int3 \
		type_desc.int3 \
		univ.int3

# RULE foreign_deps_for_mh
tdigest_mut.$O tdigest_mut.pic_o : array.mh

# RULE int0_on_date0
tdigest_mut.int0 : tdigest_mut.date0
	@:

# RULE int_on_date
tdigest_mut.int : tdigest_mut.date
	@:

# RULE int2_on_date
tdigest_mut.int2 : tdigest_mut.date
	@:

# RULE int3_on_date3
tdigest_mut.int3 : tdigest_mut.date3
	@:

# RULE opt_on_opt_date
tdigest_mut.opt : tdigest_mut.optdate
	@:

# RULE trans_opt_on_trans_opt_date
tdigest_mut.trans_opt : tdigest_mut.trans_opt_date
	@:

